package Enum;

public enum CellContent {
    EMPTY,
    WALL,
    PLAYER,
    ENEMY,
    FOOD,
    POWER_UP_SPEED_INCREASE,
    POWER_UP_FREEZE_MONSTERS,
    POWER_UP_DOUBLE_SCORE,
    POWER_UP_EXTRA_LIFE,
    POWER_UP_INVINCIBLE
}